# For more information: https://laravel.com/docs/sail
version: '3'
services:
    ######APP_SERVICE parameter######
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - selenium
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    nginx:
        build:
            context: "./docker/nginx"
        depends_on:
            -   php-fpm
            -   redis
            -   selenium
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        ports:
#            port mappings, host to docker
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - sail
    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            -   ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
        expose:
            - "9000"
#    laravel-horizon:
#        build:
#            context: ./docker/laravel-horizon
#        volumes:
#            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
#            - ./docker/laravel-horizon/supervisord.d:/etc/supervisord.d
#        depends_on:
#            - php-fpm
#        extra_hosts:
#            - "dockerhost:${DOCKER_HOST_IP}"
#        networks:
#            - sail
    selenium:
        image: 'selenium/standalone-chrome:latest'
        volumes:
            - '/dev/shm:/dev/shm'
        ports:
            - '${FORWARD_SELENIUM_PORT:-4444}:4444'
            - '${FORWARD_SELENIUM_HEADFUL_PORT:-7900}:7900'
        healthcheck:
            interval: 350s
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-selenium:
        driver: local
